// Products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

// Cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
